# Numpy:

*   
NumPy (Numerical Python) is a powerful library in Python for numerical computing.
*   It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these data structures efficiently.



# Install numpy:

In [1]:
!pip install numpy

# Import numpy:

In [2]:
import numpy as np

In [4]:
a = np.array ([1,2,3])#1-D
print(a)


[1 2 3]


In [5]:
b = np.array([[1,2,3],[4,5,6]])#2-D
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])#3-D
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


# Create a array of zero:

In [7]:
np.zeros((4,6))#3 rows and 4 coloums

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# Create a array of ones:

In [8]:
np.ones((3,2,4))  #np.ones((shape_of_the_dimention , no.of_rows , no.of_columns))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

# Create a array of evenly spaced values(using step value):

In [14]:
d=np.arange(1,20,3)#steps n-1(3-1=2)
print(d)

[ 1  4  7 10 13 16 19]


In [10]:
e = np.arange(1,1000,10)
print(e)

[  1  11  21  31  41  51  61  71  81  91 101 111 121 131 141 151 161 171
 181 191 201 211 221 231 241 251 261 271 281 291 301 311 321 331 341 351
 361 371 381 391 401 411 421 431 441 451 461 471 481 491 501 511 521 531
 541 551 561 571 581 591 601 611 621 631 641 651 661 671 681 691 701 711
 721 731 741 751 761 771 781 791 801 811 821 831 841 851 861 871 881 891
 901 911 921 931 941 951 961 971 981 991]


# Create a array of evenly spaced values(no.of samples):

In [13]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Create a constant array:

In [15]:
e=np.full((3),6)#columns
print(e)
print("dim",e.ndim)#to find no of dimension

[6 6 6]
dim 1


In [16]:
#create 2D
e=np.full((3,4),6)#rows and columns
print(e)
print("no.of dimensions",e.ndim)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]
no.of dimensions 2


In [17]:
#create 3D
e=np.full((2,3,3),7)
print(e)
print("no.of dimensions",e.ndim)

[[[7 7 7]
  [7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]
  [7 7 7]]]
no.of dimensions 3


# Create a identity matrix:

In [18]:
#create a 2x2 matrix
f=np.eye(5)
print(f)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Create a array with random values:

In [19]:
np.random.random((3,4))

array([[0.18298167, 0.20386417, 0.04250283, 0.96904762],
       [0.42218832, 0.88759776, 0.86732306, 0.20879869],
       [0.96455815, 0.10065108, 0.7378031 , 0.16124416]])

In [20]:
np.random.randint(1,40)#gives integer values between the start and end

9

# Shape of an array:

In [21]:
arr=np.array([[1,2,3],
             [4,5,6],
             [7,8,9],
             [5,7,8]])
print(arr.shape)#tells how many rows and columns in array
#4 denotes no of rows
#3 denotes no of columns

(4, 3)


#to find no of elements(size) in array

In [23]:
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [6,7,8,9],
              [2,3,5,6]])
print(arr.size)

16


# Find length of the array:

In [24]:
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [6,7,8,9],
              [2,3,5,6]])
print(len(arr))
#it will count only the rows

4


# Access array elements:

Access 1D array elements using index value:


In [25]:
arr=np.array([1,2,3,4])#by index method
print(arr[3])

4


In [26]:
arr=np.array([1,2,3,4])#by index method
print(arr[-4])

1


Access 2D array elements using index values:

In [27]:
p = np.array([[1,2,3],[4,5,6]])
print(p)
print(p[1,2])     #print( variable_name [index of 1D array , index of value])

[[1 2 3]
 [4 5 6]]
6


Access 3D array using index value:

In [28]:
q = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(q)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


#arithematic operations for array index

In [31]:
#1-D arrays
arr=np.array([1,2,3,4,5,6])
print(arr[2] * arr[3] - arr[-2])#(3*4-5)

7


In [30]:
#access the element in rows and columns(by index method)
#2-D arrays
arr=np.array([[1,2,3,4],#0
              [5,6,7,8],#1
              [6,7,8,9],#2
              [2,3,5,6]])#3
print(arr[2,3])#arr[1D index,value index]

9


In [32]:
#3-D arrays
                 #0  #1d    #1
arr=np.array([[[1,2,3,4],[5,6,7,8]],#0 #2d
              [[2,3,5,6],[3,4,7,8]],#1
              [[2,4,6,8],[4,5,7,8]],#2
              [[5,6,9,8],[5,3,2,6]]])#3
#access by index
print(arr[2,1,1])#(2D,1D,element)

5


# Data types in numpy



1. i - integer
2. b - boolean
3. f - float
4. c - complex
5. M - Datetime
5. O - object
6. S - string

In [33]:
arr=np.array([1,2,3,4],dtype='f')
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


In [34]:
arr=np.array([1.4,2.5,3.3,4.1],dtype='i')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [35]:
#change data type from float to integer using 'i' as parameter value
arr=np.array([1.3,2.2,3.1,4.5])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3 4]
int32


In [36]:
#change data type from integer to boolean
arr=np.array([1,0,3,4,-9])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True  True  True]
bool


In [37]:
#type convertion int to complex
t = np.array([1,2,3],dtype='c')
print(t)
print(t.dtype)

[b'1' b'2' b'3']
|S1


# Copy Method:

*   The .copy() method is used to create a deep copy of an array.
*   This means that the copied array has its own separate memory location, and changes to the original array do not affect the copied array.




In [38]:
#copy method
a=np.array([1,2,3,4])
b=a.copy()
a[2]=9
print(a)
print(b)

[1 2 9 4]
[1 2 3 4]


View Method:

*   The .view() method creates a shallow copy (or view) of an array.
*   This means that the new array shares the same data as the original array but has a different object identity.

*   Any modifications made to one array will affect the other.


In [39]:
#view method
a=np.array([1,2,3,4])
b=a.view()
a[2]=9
print(a)
print(b)

[1 2 9 4]
[1 2 9 4]


# Reshaping array:

*   changing the shape of an array.
*   we can add or remove the numbers.



In [40]:
#convert the following 1-D arrays into 2-D arrays with 12 elements
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.size)#1-D
newarr=arr.reshape(4,3)#(row,column)
print(newarr)#2-D

12
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [41]:
#convert the following 1-D array into 3-D arrays with 12 elements
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.size)#1-D
newarr=arr.reshape(2,3,2)#(shape,row,column)
print(newarr)#3-D

12
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [42]:
#convert the following 2-D arrays into 3-D arrays
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr.size)#2-D
newarr=arr.reshape(2,3,2)#(shape,row,column)
print(newarr)#3-D

12
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [43]:
#convert the following 1-D arrays into 3-D arrays
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.size)#1-D
newarr=arr.reshape(3,2,2)#(shape,row,column)
print(newarr)#3-D

12
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


# Arthmetic operations:

In [44]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.sqrt(a))
print(np.sqrt(b))

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[1.         1.41421356 1.73205081 2.        ]
[2.23606798 2.44948974 2.64575131 2.82842712]


#sorting arrays:

*   It means putting elements in an ordered sequence(ascending order).




In [45]:
a=np.array([3,4,2,1,6,5])
print(np.sort(a))

[1 2 3 4 5 6]


# Slicing Method:

Positive Slicing

In [46]:
#slice elements from index 1 to index 5 from the following array
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[1:7])#starting point:ending point(n-1)

[2 3 4 5 6 7]


In [47]:
#slice elements from index 4 to the end of the array
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[4:])

[ 5  6  7  8  9 10]


In [48]:
#slice elements from the beginning to index 6
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[:6])

[1 2 3 4 5 6]


Negative Slicing

In [49]:
#slice from the index 3 from the end to index 1 from the end
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[-3:-1])

[8 9]


In [50]:
#slice from the index 4 from the end to index 2 from the end
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[-4:-2])

[7 8]


1-D & 2-D & 3-D Slicing

In [55]:
#use the step value to determine the step of the slicing
a=np.array([1,2,3,4,5,6,7,8,9,4,1,5,3,6,2,7,2])#1-D
print(a[0:13:2]) #step is apply like step-1

[1 3 5 7 9 1 3]


In [52]:
#return every other element from the entire array
a=np.array([1,2,3,4,5,6,7,8,9,4,1,5,3,6,2,7,2])
print(a[::3])

[1 4 7 4 3 7]


In [53]:
#slicing 2-D array
#from the second element,slice elements from index 1 to index 4
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[1,1:4])

[7 8 9]


In [54]:
#return both element index 3
a=np.array([[1,2,3,4,5],#0
            [6,7,8,9,10],#1
            [6,7,8,9,10],#2 1D
            [6,7,8,9,10]])#3 1D
print(a[0:2,3])#(1D element)

[4 9]
